const key='dayflow-data';
const state=JSON.parse(localStorage.getItem(key)||'{"tasks":[],"notes":[],"events":[]}');
let page='home', timerSeconds=25*60, running=false, timerId;
const save=()=>localStorage.setItem(key,JSON.stringify(state));
const today=new Date(); const pad=n=>String(n).padStart(2,'0'); const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
function layout(content){return `<div class="page">${content}</div>`}
function render(){
 const app=document.querySelector('#app');
 if(page==='home'){app.innerHTML=layout(document.querySelector('#home-template').innerHTML);document.querySelector('#todayDate').textContent=today.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric'});document.querySelector('#todayDay').textContent=today.toLocaleDateString('ja-JP',{weekday:'long'});const incomplete=state.tasks.filter(t=>!t.done);document.querySelector('#taskProgress').textContent=`残り ${incomplete.length} 件`;document.querySelector('#nextTask').textContent=incomplete[0]?.title||'次のタスクを追加して、今日を始めよう。'}
 else if(page==='tasks') app.innerHTML=layout(`<p class="eyebrow">01 / TASKS</p><h2 class="page-title">タスク</h2><p class="sub">頭の中を、次にやるひとつへ。</p><section class="panel"><form class="task-form" id="taskForm"><input id="taskInput" required autocomplete="off" placeholder="新しいタスク"/><button class="primary">追加</button></form><div class="tabs"><button class="tab active" data-filter="all">すべて</button><button class="tab" data-filter="today">今日</button><button class="tab" data-filter="open">未完了</button></div><ul class="task-list" id="taskList"></ul></section>`)
 else if(page==='notes') app.innerHTML=layout(`<p class="eyebrow">03 / QUICK NOTES</p><h2 class="page-title">クイックメモ</h2><p class="sub">忘れる前に、置いておく。</p><section class="panel"><textarea class="note-input" id="noteInput" placeholder="いま考えていること…"></textarea><button class="primary" id="saveNote">メモを保存</button></section><section class="notes-grid" id="notesGrid"></section>`)
 else if(page==='calendar') calendar(); else if(page==='focus') focus();
 document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{page=x.dataset.page;render()});document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));bind();app.focus();
}
function bind(){if(page==='tasks'){document.querySelector('#taskForm').onsubmit=e=>{e.preventDefault();state.tasks.unshift({id:Date.now(),title:taskInput.value,done:false,created:dateKey(today)});save();render()};drawTasks('all');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawTasks(b.dataset.filter)})} if(page==='notes'){document.querySelector('#saveNote').onclick=()=>{const v=noteInput.value.trim();if(v){state.notes.unshift({id:Date.now(),body:v});save();render()}};drawNotes()}if(page==='focus'){document.querySelector('#startTimer').onclick=startTimer;document.querySelector('#resetTimer').onclick=()=>{clearInterval(timerId);running=false;timerSeconds=25*60;updateTimer()}}}
function drawTasks(filter){let a=state.tasks;if(filter==='open')a=a.filter(x=>!x.done);if(filter==='today')a=a.filter(x=>x.created===dateKey(today));taskList.innerHTML=a.length?a.map(t=>`<li class="${t.done?'done':''}"><input class="check" type="checkbox" ${t.done?'checked':''} data-check="${t.id}"><span>${escapeHtml(t.title)}</span><button class="delete" data-delete="${t.id}" aria-label="削除">×</button></li>`).join(''):'<li><span>まだタスクはありません。</span></li>';document.querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{state.tasks.find(t=>t.id==e.dataset.check).done=e.target.checked;save();drawTasks(filter)});document.querySelectorAll('[data-delete]').forEach(e=>e.onclick=()=>{state.tasks=state.tasks.filter(t=>t.id!=e.dataset.delete);save();drawTasks(filter)})}
function drawNotes(){notesGrid.innerHTML=state.notes.map(n=>`<article class="note">${escapeHtml(n.body)}</article>`).join('')||'<p class="sub">メモはまだありません。</p>'}function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function calendar(){const y=today.getFullYear(),m=today.getMonth(),first=new Date(y,m,1),start=first.getDay(),days=new Date(y,m+1,0).getDate();let cells=['日','月','火','水','木','金','土'].map(d=>`<div class="cal-day"><strong>${d}</strong></div>`);for(let i=0;i<start;i++)cells.push('<div class="cal-day"></div>');for(let d=1;d<=days;d++){const k=dateKey(new Date(y,m,d));cells.push(`<div class="cal-day ${k===dateKey(today)?'today':''}"><strong>${d}</strong>${state.events.filter(e=>e.date===k).map(e=>`<div class="event">${escapeHtml(e.title)}</div>`).join('')}</div>`)}document.querySelector('#app').innerHTML=layout(`<p class="eyebrow">02 / CALENDAR</p><h2 class="page-title">${today.toLocaleDateString('ja-JP',{year:'numeric',month:'long'})}</h2><p class="sub">予定に、余白をつくる。</p><section class="panel"><form class="event-form" id="eventForm"><input id="eventDate" type="date" value="${dateKey(today)}" required><input id="eventTitle" placeholder="予定のタイトル" required><button class="primary">追加</button></form><div class="calendar-grid">${cells.join('')}</div></section>`);eventForm.onsubmit=e=>{e.preventDefault();state.events.push({id:Date.now(),date:eventDate.value,title:eventTitle.value});save();render()};document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{page=x.dataset.page;render()});document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
function focus(){document.querySelector('#app').innerHTML=layout(`<section class="focus-wrap"><p class="eyebrow">04 / FOCUS</p><h2 class="page-title">ひとつに集中する。</h2><p class="sub">25分だけ、余計なものから離れる。</p><div class="focus-task"><input placeholder="何に集中しますか？"></div><div class="timer" id="timer">25:00</div><div class="timer-controls"><button class="primary" id="startTimer">はじめる</button><button class="outline" id="resetTimer">リセット</button></div></section>`);document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>{page=x.dataset.page;render()});document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===page));}
function updateTimer(){timer.textContent=`${pad(Math.floor(timerSeconds/60))}:${pad(timerSeconds%60)}`;if(timerSeconds===0){clearInterval(timerId);running=false;startTimer.textContent='もう一度';if(Notification.permission==='granted')new Notification('Dayflow',{body:'ポモドーロが完了しました。'});else alert('ポモドーロが完了しました。')}}function startTimer(){if(running)return;running=true;startTimer.textContent='集中中…';timerId=setInterval(()=>{timerSeconds--;updateTimer()},1000)}
notificationButton.onclick=async()=>{if(!('Notification'in window))return alert('このブラウザは通知に対応していません。');const p=await Notification.requestPermission();alert(p==='granted'?'通知を有効にしました。':'通知は許可されませんでした。')};render();
